# Smart Valenbici
## Carga de datos

In [1]:
import os
import glob
import zipfile
import pandas as pd

carpeta_x = "valenbici"
lista_dataframes = []

i = 0
for ruta_zip in glob.glob(os.path.join(carpeta_x, "*.zip")):
    print(f'{i:03}/954 -> {i*100/954}',end="\r")
    i+=1
    with zipfile.ZipFile(ruta_zip, 'r') as z:
        for nombre_archivo in z.namelist():
            if nombre_archivo.endswith('.csv'):
                with z.open(nombre_archivo) as f:
                    df_temporal = pd.read_csv(f,sep=';')
                    df_temporal['origen_zip'] = os.path.basename(ruta_zip)
                    df_temporal['origen_csv'] = nombre_archivo
                    
                    lista_dataframes.append(df_temporal)


df_total = pd.concat(lista_dataframes, ignore_index=True)

951/954 -> 99.6855345911949763

C:\Users\xboxp\AppData\Local\Temp\ipykernel_17172\3501240656.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_total = pd.concat(lista_dataframes, ignore_index=True)

In [2]:
df_total.head()

,gid,name,number_,address,open,available,free,total,ticket,updated_at,...,origen_zip,origen_csv,Direccion,Numero,Activo,Bicis_disponibles,Espacios_libres,Espacios_totales,fecha_actualizacion,update_jcd
0,901601.0,021_JUAN_LLORENS_29,21.0,Juan Llorens - Literato Gabriel Miró,T,13.0,3.0,16.0,T,31/12/2022 23:49:59,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,901632.0,52_C/ LUIS GARCIA BERLANGA,52.0,Luis García Berlanga Martí - Menorca,T,14.0,11.0,25.0,T,31/12/2022 23:49:59,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,901626.0,46_AVDA. INSTITUTO OBRERO DE VALENCIA,46.0,Pintor Luis Arcas - Inst. Obrero Valenciano,T,5.0,14.0,20.0,F,31/12/2022 23:49:59,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,901630.0,50_AVDA. AUTOPISTA DEL SALER,50.0,Autopista del Saler - Antonio Ferrandis (C.C. ...,T,0.0,40.0,40.0,T,31/12/2022 23:49:59,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,901646.0,066_GUILLEN DE ANGLESOLA,66.0,Guillem de Anglesola - Av. Puerto,T,10.0,14.0,25.0,F,31/12/2022 23:49:59,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

df_total['direccion'] = df_total['Direccion'].combine_first(df_total['address'])

df_total['bicis_disponibles'] = df_total['Bicis_disponibles'].combine_first(df_total['available'])

df_total['espacios_libres'] = df_total['Espacios_libres'].combine_first(df_total['free'])

df_total['espacios_totales'] = df_total['Espacios_totales'].combine_first(df_total['total'])

df_total['fecha_actualizacion_final'] = df_total['fecha_actualizacion'].combine_first(df_total['updated_at'])

df_total.head()

,gid,name,number_,address,open,available,free,total,ticket,updated_at,...,Bicis_disponibles,Espacios_libres,Espacios_totales,fecha_actualizacion,update_jcd,direccion,bicis_disponibles,espacios_libres,espacios_totales,fecha_actualizacion_final
0,901601.0,021_JUAN_LLORENS_29,21.0,Juan Llorens - Literato Gabriel Miró,T,13.0,3.0,16.0,T,31/12/2022 23:49:59,...,NaN,NaN,NaN,NaN,NaN,Juan Llorens - Literato Gabriel Miró,13.0,3.0,16.0,31/12/2022 23:49:59
1,901632.0,52_C/ LUIS GARCIA BERLANGA,52.0,Luis García Berlanga Martí - Menorca,T,14.0,11.0,25.0,T,31/12/2022 23:49:59,...,NaN,NaN,NaN,NaN,NaN,Luis García Berlanga Martí - Menorca,14.0,11.0,25.0,31/12/2022 23:49:59
2,901626.0,46_AVDA. INSTITUTO OBRERO DE VALENCIA,46.0,Pintor Luis Arcas - Inst. Obrero Valenciano,T,5.0,14.0,20.0,F,31/12/2022 23:49:59,...,NaN,NaN,NaN,NaN,NaN,Pintor Luis Arcas - Inst. Obrero Valenciano,5.0,14.0,20.0,31/12/2022 23:49:59
3,901630.0,50_AVDA. AUTOPISTA DEL SALER,50.0,Autopista del Saler - Antonio Ferrandis (C.C. ...,T,0.0,40.0,40.0,T,31/12/2022 23:49:59,...,NaN,NaN,NaN,NaN,NaN,Autopista del Saler - Antonio Ferrandis (C.C. ...,0.0,40.0,40.0,31/12/2022 23:49:59
4,901646.0,066_GUILLEN DE ANGLESOLA,66.0,Guillem de Anglesola - Av. Puerto,T,10.0,14.0,25.0,F,31/12/2022 23:49:59,...,NaN,NaN,NaN,NaN,NaN,Guillem de Anglesola - Av. Puerto,10.0,14.0,25.0,31/12/2022 23:49:59

In [4]:
df_total.drop(
    columns=[
        'Direccion', 'address',
        'Bicis_disponibles', 'available',
        'Espacios_libres', 'free',
        'Espacios_totales', 'total',
        'fecha_actualizacion', 'updated_at'
    ], 
    inplace=True 
)

In [5]:
df_total.head()

,gid,name,number_,open,ticket,globalid,created_user,created_date,last_edited_user,last_edited_date,...,origen_zip,origen_csv,Numero,Activo,update_jcd,direccion,bicis_disponibles,espacios_libres,espacios_totales,fecha_actualizacion_final
0,901601.0,021_JUAN_LLORENS_29,21.0,T,T,{B8591BB2-ECAD-4661-A099-710D670A5735},NaN,NaN,NaN,NaN,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,Juan Llorens - Literato Gabriel Miró,13.0,3.0,16.0,31/12/2022 23:49:59
1,901632.0,52_C/ LUIS GARCIA BERLANGA,52.0,T,T,{806C8521-E7DC-4278-8814-94946C412DD9},NaN,NaN,NaN,NaN,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,Luis García Berlanga Martí - Menorca,14.0,11.0,25.0,31/12/2022 23:49:59
2,901626.0,46_AVDA. INSTITUTO OBRERO DE VALENCIA,46.0,T,F,{3D5DA54B-F3F3-4D7E-8280-5538A1E77621},NaN,NaN,NaN,NaN,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,Pintor Luis Arcas - Inst. Obrero Valenciano,5.0,14.0,20.0,31/12/2022 23:49:59
3,901630.0,50_AVDA. AUTOPISTA DEL SALER,50.0,T,T,{818538C0-0D0D-417B-97A2-916B511C4D58},NaN,NaN,NaN,NaN,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,Autopista del Saler - Antonio Ferrandis (C.C. ...,0.0,40.0,40.0,31/12/2022 23:49:59
4,901646.0,066_GUILLEN DE ANGLESOLA,66.0,T,F,{97939B65-E808-4A63-990F-8B8C64190431},NaN,NaN,NaN,NaN,...,01-01-2023.zip,valenbici_01-01-2023_00-00-02.csv,NaN,NaN,NaN,Guillem de Anglesola - Av. Puerto,10.0,14.0,25.0,31/12/2022 23:49:59

In [6]:
df_total.shape

(24959284, 22)

In [7]:
df_total = df_total.dropna(axis=1, how='all')
df_total = df_total.drop(columns=['origen_zip', 'origen_csv'], errors='ignore')

In [8]:
df_total['numero'] = df_total['number_'].combine_first(df_total['Numero'])
df_total['activo'] = df_total['Activo'].combine_first(df_total['open'])
df_total = df_total.drop(columns=['number_', 'Numero','open','Activo'], errors='ignore')

In [9]:
df_total.head()

,gid,name,ticket,globalid,geo_shape,geo_point_2d,update_jcd,direccion,bicis_disponibles,espacios_libres,espacios_totales,fecha_actualizacion_final,numero,activo
0,901601.0,021_JUAN_LLORENS_29,T,{B8591BB2-ECAD-4661-A099-710D670A5735},"{""coordinates"": [-0.39021443540491124, 39.4723...","39.4723713328859,-0.39021443540491124",NaN,Juan Llorens - Literato Gabriel Miró,13.0,3.0,16.0,31/12/2022 23:49:59,21.0,T
1,901632.0,52_C/ LUIS GARCIA BERLANGA,T,{806C8521-E7DC-4278-8814-94946C412DD9},"{""coordinates"": [-0.3463402980947426, 39.45603...","39.45603425797373,-0.3463402980947426",NaN,Luis García Berlanga Martí - Menorca,14.0,11.0,25.0,31/12/2022 23:49:59,52.0,T
2,901626.0,46_AVDA. INSTITUTO OBRERO DE VALENCIA,F,{3D5DA54B-F3F3-4D7E-8280-5538A1E77621},"{""coordinates"": [-0.35878734087160885, 39.4555...","39.455509261762266,-0.35878734087160885",NaN,Pintor Luis Arcas - Inst. Obrero Valenciano,5.0,14.0,20.0,31/12/2022 23:49:59,46.0,T
3,901630.0,50_AVDA. AUTOPISTA DEL SALER,T,{818538C0-0D0D-417B-97A2-916B511C4D58},"{""coordinates"": [-0.3528593228128155, 39.45331...","39.453318252515686,-0.3528593228128155",NaN,Autopista del Saler - Antonio Ferrandis (C.C. ...,0.0,40.0,40.0,31/12/2022 23:49:59,50.0,T
4,901646.0,066_GUILLEN DE ANGLESOLA,F,{97939B65-E808-4A63-990F-8B8C64190431},"{""coordinates"": [-0.3462612916525901, 39.46427...","39.46427128532339,-0.3462612916525901",NaN,Guillem de Anglesola - Av. Puerto,10.0,14.0,25.0,31/12/2022 23:49:59,66.0,T

In [10]:
df_total.to_csv("valenbici_limpio.csv", index=False)